"""添加qq帐号字段

Revision ID: 6389b2c38169
Revises: 04e4d20f1200
Create Date: 2019-01-02 21:19:56.106473

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6389b2c38169'
down_revision = '04e4d20f1200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('qq_account', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'qq_account')
    # ### end Alembic commands ###
