"""empty message

Revision ID: 757248384f2b
Revises: db42cf04b0c2
Create Date: 2019-01-04 15:38:14.413796

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '757248384f2b'
down_revision = 'db42cf04b0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
